search:
    Dylvn\Bundle\FaqBundle\Entity\Category:
        alias: dylvn_faq_category
        route:
            name: dylvn_faq_category_view
            parameters:
                id: id
        search_template: '@DylvnFaqBundle/Category/searchResult.html.twig'
        fields:
            -   name: code
                target_type: text
                target_fields:
                    - code
            -
                name: defaultTitle
                target_type: text
                target_fields:
                    - defaultTitle

    Dylvn\Bundle\FaqBundle\Entity\Item:
        alias: dylvn_faq_item
        route:
            name: dylvn_faq_item_view
            parameters:
                id: id
        search_template: '@DylvnFaq/Item/searchResult.html.twig'
        fields:
            -
                name: defaultQuestion
                target_type: text
                target_fields:
                    - defaultQuestion
            -
                name: defaultAnswer
                target_type: text
                target_fields:
                    - defaultAnswer
            -
                name: categoryItems
                relation_type: one-to-many
                relation_fields:
                    -
                        name: code
                        target_type: text
                        target_fields:
                            - categoryCode
